apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app
  namespace: gitops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitops-app
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
        - name: app
          image: ssm0712/gitops-full-project:6745be44769d6ce5e3bb43730e49bb885047283e
          ports:
          - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
